// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN28C0OsH3Datw9GNCD5QJX9siFhZrolY',
    appId: '1:180470178962:web:f1e1c90e4a880cda75324b',
    messagingSenderId: '180470178962',
    projectId: 'blocmastered',
    authDomain: 'blocmastered.firebaseapp.com',
    storageBucket: 'blocmastered.appspot.com',
    measurementId: 'G-K0NFBPK1VH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_NgSOCfmM5NF-xaYqFxE0LWcdMoi3xDI',
    appId: '1:180470178962:android:87566e7eae2542f975324b',
    messagingSenderId: '180470178962',
    projectId: 'blocmastered',
    storageBucket: 'blocmastered.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAobF3rhSnRrS0ygAcYx30IHnuKv3pcXjQ',
    appId: '1:180470178962:ios:f1437d68d496d92d75324b',
    messagingSenderId: '180470178962',
    projectId: 'blocmastered',
    storageBucket: 'blocmastered.appspot.com',
    iosBundleId: 'com.example.blocMastered',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAobF3rhSnRrS0ygAcYx30IHnuKv3pcXjQ',
    appId: '1:180470178962:ios:be1c11f817b7d1e975324b',
    messagingSenderId: '180470178962',
    projectId: 'blocmastered',
    storageBucket: 'blocmastered.appspot.com',
    iosBundleId: 'com.example.blocMastered.RunnerTests',
  );
}
